### ISSUE TITLE
Exception java.lang.IllegalArgumentException: No such namespace: , using clojars 0.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by josesanch** [danielsz/system#80]
The exceptions is in runtime.
The code compiles correctly. However, if you run (start) you get this error.

Exception in thread "main" java.lang.IllegalArgumentException: No such namespace: , compiling:(/tmp/form-init952470378900861673.clj:1:72)
	at clojure.lang.Compiler.load(Compiler.java:7391)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No such namespace: 
	at clojure.lang.Var.find(Var.java:141)
	at clojure.core$find_var.invokeStatic(core.clj:1928)
	at clojure.core$find_var.invoke(core.clj:1923)
	at system.repl$init.invokeStatic(repl.clj:18)
	at system.repl$init.invoke(repl.clj:15)
	at system.repl$start.invokeStatic(repl.clj:23)
	at system.repl$start.invoke(repl.clj:20)
	at dondeestamigrua.core$_main.invokeStatic(core.clj:19)
	at dondeestamigrua.core$_main.doInvoke(core.clj:14)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval5.invokeStatic(form-init952470378900861673.clj:1)
	at user$eval5.invoke(form-init952470378900861673.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	... 14 more

**Comment by danielsz** [comment]
Yes, you need to pass a valid Var. 

I'll make it spit a better error message.

**Comment by danielsz** [comment]
OK, you should get a clearer error with the latest snapshot (which is already deployed).

Did you sort it out?

**Comment by josesanch** [comment]
Works perfect using #'dev-system. I had dev-system before and worked with the previous snapshot.

Thank you very much

**Comment by danielsz** [comment]
Excellent. 

We do know very late binding on the SystemMap which gives users the opportunity to not only restart an existing system, but to modify the SystemMap itselft and having that restarted.

Thank you, @josesanch .
